version: '3.8'

services:
  notes:
    build:
      context: ./
    command: ./wait-for-postgres.sh db ./notes
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=${DB_PASSWORD}

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5436:5432
